name: talking_baby_flutter
description: "Mobil app for [Company Name Here] child toy management."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization Dependencies
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Routing Dependencies
  go_router: ^13.0.1

  # UI Dependencies
  google_fonts: ^6.1.0

  # Other Dependencies
  shared_preferences: ^2.2.3
  esp_smartconfig: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
